# Generated by Django 5.1.7 on 2025-04-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('age', models.CharField(max_length=1024)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('price', models.IntegerField(null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
