# Generated by Django 5.1.7 on 2025-03-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Not Specified', 'NS')], default='Not Specified', max_length=128),
        ),
    ]
