# Generated by Django 5.1.7 on 2025-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Not Specified', 'NS')], default='Not Specified', max_length=128),
        ),
    ]
