# Generated by Django 5.1.7 on 2025-03-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=1024)),
                ('event_date', models.DateField()),
                ('event_description', models.CharField(max_length=2048)),
                ('event_min_budget', models.IntegerField(default=10)),
                ('event_max_budget', models.IntegerField()),
                ('is_draw', models.BooleanField(default=False)),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
