# Generated by Django 5.1.7 on 2025-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventparticipant_drawn_name'),
        ('wishList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='wishList.item'),
        ),
    ]
